fix: relative aggregation of samples for variants and lineages over time plots
IKIM-Essen/uncovar pull request #382
Opened 2021-12-08 09:57 UTC by AKBrueggemann

# Description

## Related Issue

## Checklist

- [ ] I've formatted the PR title in accordance with the [structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] I've updated the code style using `snakefmt workflow/` and `black workflow/` if needed.
- [ ] I've updated or supplemented the documentation as needed.
- [x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/IKIM-Essen/uncovar/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I've read the [`CONTRIBUTING.md`](https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md) guide.

2021-12-08 10:48 UTC, thomasbtf requested changes
Nice easy fix for the problem. 

Could you please add a plot with only one sample (for one date) and another with several samples, distributed over several dates?

2021-12-08 10:48 UTC, thomasbtf commented on workflow/scripts/plot-lineages-over-time.py
> +    ] = "other (< low occ.)"
Please insert here the masking threshold number. It would make sense to cast it to an integer before.

2021-12-08 10:48 UTC, thomasbtf commented on workflow/scripts/plot-variants-over-time.py
> +        ] = "other (< low occ.)"
same here, see above

2021-12-08 10:49 UTC, thomasbtf commented
Ah and please fill out the Description, Related Issue and Checklist of this PR ;)

2021-12-08 13:51 UTC, AKBrueggemann commented
<img width="776" alt="VariantplotsNewRelative" src="https://user-images.githubusercontent.com/90249112/145219651-780fc6b9-57f0-4536-810b-d345215da54a.png">

2021-12-09 12:18 UTC, AKBrueggemann commented
Lineages over time of 5 samples:
<img width="843" alt="5SamplesLineages" src="https://user-images.githubusercontent.com/90249112/145394804-c33ba919-e0c9-4f28-8f9c-6c8194341812.png">
Lineages over time of 1 sample:
<img width="782" alt="OneSampleLineages" src="https://user-images.githubusercontent.com/90249112/145394831-6e8c7de3-cc2e-4c27-8c37-d8addc4bba6c.png">

2021-12-09 12:21 UTC, AKBrueggemann commented
Variants over time of the S-ORF of one sample:
<img width="648" alt="OneSampleSVariants" src="https://user-images.githubusercontent.com/90249112/145395218-ab79503d-f930-4465-bc0c-df3c308b55f0.png">
Variants over time of the S-ORF of five samples:
<img width="842" alt="5SamplesVariantsS" src="https://user-images.githubusercontent.com/90249112/145395292-cdf5248c-e57a-4548-9100-81e7a2ffdacf.png">

2021-12-09 19:22 UTC, thomasbtf approved these changes

2021-12-09 19:22 UTC, thomasbtf commented
Just a quick pointer to string formatting best practices: https://realpython.com/python-string-formatting/ :)

2021-12-10 12:29 UTC, merged