feat: add pangolin call table
IKIM-Essen/uncovar pull request #397
Opened 2021-12-13 19:21 UTC by thomasbtf

# Description

Adds a table, which contains pangolin of various stages throughout the workflow (scaffolded-, polished-, masked polished-, pseudo-, consensus-, masked consensus-sequences)

## Related Issue

closes #211
closes #166

## Checklist

- [X] I've formatted the PR title in accordance with the [structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
- [X] I've updated the code style using `snakefmt workflow/` and `black workflow/` if needed.
- [ ] I've updated or supplemented the documentation as needed.
- [X] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/IKIM-Essen/uncovar/blob/master/CODE_OF_CONDUCT.md) document.
- [X] I've read the [`CONTRIBUTING.md`](https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md) guide.

2021-12-13 23:56 UTC, alethomas approved these changes

2021-12-15 08:56 UTC, alethomas requested changes

2021-12-15 08:56 UTC, alethomas commented on docs/consumer-guide/index.md
> +This section of the documentation is focused on final data interpreted,
These lines sound difficult

2021-12-15 08:56 UTC, alethomas commented on docs/consumer-guide/report-structure.md
> +- **Consensus** Sequences: Using corrected reads and the the virus reference
Double the

2021-12-15 08:56 UTC, alethomas commented on docs/consumer-guide/report-structure.md
> +- **Pseudo** Sequences: Sequences that generated based on the virus reference
'are' missing

2021-12-15 09:00 UTC, thomasbtf commented on docs/consumer-guide/report-structure.md
> +- **Pseudo** Sequences: Sequences that generated based on the virus reference
:+1

2021-12-15 09:00 UTC, thomasbtf commented on docs/consumer-guide/report-structure.md
> +- **Consensus** Sequences: Using corrected reads and the the virus reference
:+1

2021-12-15 09:05 UTC, thomasbtf commented on docs/consumer-guide/index.md
> +This section of the documentation is focused on final data interpreted,
Thanks! See cd7cd99

2021-12-15 09:05 UTC, thomasbtf commented on docs/consumer-guide/report-structure.md
> +- **Consensus** Sequences: Using corrected reads and the the virus reference
Thanks! See cd7cd99

2021-12-15 09:05 UTC, thomasbtf commented on docs/consumer-guide/report-structure.md
> +- **Pseudo** Sequences: Sequences that generated based on the virus reference
Thanks! See cd7cd99

2021-12-15 11:35 UTC, alethomas requested changes

2021-12-15 11:35 UTC, alethomas commented on docs/consumer-guide/index.md
> +guidance for interpreting the results produced by UnCoVar is provided.
```suggestion
This section of the documentation is focused on data interpretation, targeting
virologists, epidemiologists and other involved scientists. General guidance for
interpreting the results produced by UnCoVar is provided
```

2021-12-15 12:27 UTC, merged