feat: make incoming and archive structure data-handling optional
IKIM-Essen/uncovar pull request #443
Opened 2022-01-06 16:16 UTC by lenakinzel

# Description

- Added a flag named "use-data-handling" to the config file to make incoming and archive structure data-handling optional
- this enables to to switch whether the workflow should archive its results and needs the incoming, archive and data directories (=True) or not (=False)

## Related Issue

#327 

## Checklist

- [x] I've formatted the PR title in accordance with the [structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I've updated the code style using [`pre-commit`](https://ikim-essen.github.io/uncovar/dev-guide/contributing/#pre-commit) if needed.
- [ ] I've updated or supplemented the documentation as needed.
- [x] I've read the [`CODE_OF_CONDUCT.md`] document.
- [x] I've read the [`CONTRIBUTING.md`] guide.

[`CODE_OF_CONDUCT.md`]: https://github.com/IKIM-Essen/uncovar/blob/master/CODE_OF_CONDUCT.md
[`CONTRIBUTING.md`]: https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md

2022-01-11 14:07 UTC, thomasbtf commented
You can just run `pre-commit run --all-files`. Normally this will fix all the formatting errors :) See https://ikim-essen.github.io/uncovar/dev-guide/contributing/#pre-commit for more information :)

2022-01-19 12:44 UTC, alethomas requested changes
I'd prefer two separate flags to have also incoming data handling without archiving and vice versa

2022-02-14 14:38 UTC, thomasbtf approved these changes
LGTM. @alethomas could you also please review?

2022-02-16 12:08 UTC, alethomas approved these changes

2022-02-16 15:36 UTC, merged