fix: changes in path requirements for snakedeploy
IKIM-Essen/uncovar pull request #590
Opened 2023-03-08 15:27 UTC by AKBrueggemann

# Description

 Changed the path fetching in common.smk -> get_resource(). Should fetch the total link if snake deploy is used so files can be used from the resources folder in the repository.

## Related Issue

## Checklist

- [x] I've formatted the PR title in accordance with the [structure of the conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I've updated the code style using [`pre-commit`](https://ikim-essen.github.io/uncovar/dev-guide/contributing/#pre-commit) if needed.
- [x] I've updated or supplemented the documentation as needed.
- [x] I've read the [`CODE_OF_CONDUCT.md`] document.
- [x] I've read the [`CONTRIBUTING.md`] guide.

[`CODE_OF_CONDUCT.md`]: https://github.com/IKIM-Essen/uncovar/blob/master/CODE_OF_CONDUCT.md
[`CONTRIBUTING.md`]: https://github.com/IKIM-Essen/uncovar/blob/master/CONTRIBUTING.md

2023-03-09 13:29 UTC, johanneskoester requested changes
I don't think this will work in all cases (although it might work in your tests now). There is a better solution:
Whenever you use a resource, you should use `workflow.source_path()

2023-03-09 13:29 UTC, johanneskoester commented on workflow/rules/common.smk
> +        return str((Path(workflow.snakefile).parent.parent.parent / "resources") / name)
This is much simpler, and also more portable as it also works in the cloud:
```suggestion
    return workflow.source_path(f"../../resources/{name}")
```
In addition, I suggest to move the resources subfolder into the workflow subfolder in the future. This makes the separation between resources that come together with the workflow and resources that are downloaded by the workflow cleaner.

2023-03-13 14:47 UTC, johanneskoester commented
The error is indeed a bug in Snakemake. Fix is here: https://github.com/snakemake/snakemake/pull/2170

2023-03-13 14:48 UTC, johanneskoester commented
Thanks a lot @AKBrueggemann! Once the PR is merged and release, you can rerun the CI in this PR here, as it should automatically take the latest Snakemake.

2023-03-13 15:16 UTC, AKBrueggemann commented
Thank you very much @johanneskoester!

2023-03-20 13:35 UTC, johanneskoester commented
Needs another fix: https://github.com/snakemake/snakemake/pull/2179

2023-03-23 12:53 UTC, merged